name: telcorain_env2
channels:
  - defaults
  - conda-forge
dependencies:
  - numba=0.62.1
  - sqlite=3.51.0
  - lz4-c=1.9.4
  - mkl_random=1.3.0
  - libzlib=1.3.1
  - zstd=1.5.7
  - bzip2=1.0.8
  - openssl
  - numpy
  - pycomlink
  - influxdb-client
  - pykrige
  - tqdm
  - pandas
  - intel-openmp=2025.0.0
  - tbb=2022.0.0
  - xz=5.6.4
  - pip=25.3
  - libllvm20=20.1.8
  - libffi=3.4.4
  - ca-certificates
  - blas=1.0
  - expat=2.7.3
  - llvmlite=0.45.1
  - zlib=1.3.1
  - setuptools=80.9.0
  - mkl=2025.0.0
  - python=3.10.19
  - mkl_fft=2.1.1
  - wheel=0.45.1
  - tbb-devel=2022.0.0
  - mkl-service=2.5.2
  - tk=8.6.15
  - cython
  - compilers
  - tensorflow=2.13
  - pip:
        - torch==2.1.0
        - torchvision==0.16.0
        - torchaudio==2.1.0
        - mariadb=1.1.14
