name: telcorain_env
channels:
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - intel-openmp=2025.0.0
  - libffi=3.4.4
  - libllvm20=20.1.8
  - libzlib=1.3.1
  - llvmlite=0.45.1
  - lz4-c=1.9.4
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - numba=0.62.1
  - numpy-base=1.26.4
  - openssl=3.0.18
  - pip=25.3
  - python=3.10.19
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - asttokens==3.0.1
      - astunparse==1.6.3
      - attrs==25.4.0
      - backcall==0.2.0
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - bottleneck==1.6.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - cftime==1.6.5
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - cython==3.2.1
      - decorator==5.2.1
      - defusedxml==0.7.1
      - docopt==0.6.2
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fsspec==2025.9.0
      - future==1.0.0
      - gast==0.4.0
      - google-auth==2.43.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - h5py==3.15.1
      - idna==3.11
      - influxdb-client==1.49.0
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - jupyterlab-pygments==0.3.0
      - keras==2.13.1
      - kiwisolver==1.4.9
      - libclang==18.1.1
      - mariadb==1.1.14
      - markdown==3.10
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - matplotlib-inline==0.2.1
      - mistune==3.1.4
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - netcdf4==1.7.3
      - networkx==3.3
      - numpy==1.24.3
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.1.4
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pickleshare==0.7.5
      - pillow==11.3.0
      - pipreqs==0.5.0
      - platformdirs==4.5.0
      - poligrain==0.3.1
      - prompt-toolkit==3.0.52
      - protobuf==4.25.8
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycomlink==0.5.0
      - pygments==2.19.2
      - pykrige==1.7.3
      - pyparsing==3.2.5
      - pyproj==3.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyzmq==27.1.0
      - reactivex==4.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rpds-py==0.29.0
      - rsa==4.9.1
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - shapely==2.1.2
      - six==1.17.0
      - soupsieve==2.8
      - sparse==0.17.0
      - stack-data==0.6.3
      - sympy==1.13.1
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - torch==2.1.0
      - torchaudio==2.1.0
      - torchvision==0.16.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.5.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - xarray==2023.12.0
      - yarg==0.1.9
